" Source a global configuration file if available
" XXX Deprecated, please move your changes here in /etc/vim/vimrc
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

"""
" Trop merci la conf debian vide !!!!
"""

set ruler        " show the cursor position all the time
set showcmd        " display incomplete commands
set incsearch        " do incremental searching

if &t_Co > 2 || has("gui_running")
  syntax on
  "set hlsearch
endif

set nocompatible " breaks compatibility with original vi
set backspace=indent,eol,start " allow backspace in insert mode
"set autoindent    " text indenting
"set smartindent   " as above
set tabstop=4     " number of spaces in a tab
set expandtab     " remplacer les tab par des espaces \o/
set softtabstop=4 " as above
set shiftwidth=4  " as above

set history=100   " lines of command history
set showcmd       " show incomplete commands
"set hlsearch      " highlight searched-for phrases
set incsearch     " highlight search as you type
set smarttab
"set list " affiche les caracteres louches
set tabpagemax=15

"Color
colorscheme molokai " set up a color scheme in the gvim interface

let mywinfont="Monospace:h10:cANSI"

"set number         " display current line number (désolé Julien... :/ )

"Retour a la meme position
if has("autocmd")
  "filetype plugin indent on
  "autocmd FileType text setlocal textwidth=78

" always jump to last edit position when opening a file
  autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal g`\"" |
  \ endif
endif

"Souligne la ligne en cours
set cursorline
highlight CursorLine guibg=#616668

syntax on
" Pathogen
execute pathogen#infect()
